import Footer from '@/components/landing/footer';
import Header from '@/components/landing/header';
import PolicyCard from '@/components/policy-card';
import type { Metadata } from 'next';

export const metadata: Metadata = {
	title: 'Agro App Policies',
	description: 'Generated by create next app',
};

export default async function Layout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		// <main className='flex flex-col lg:grid lg:grid-cols-7 py-12 gap-8 w-full px-6 relative'>
		<main className='flex flex-col md:flex-row  py-12 gap-8 w-full px-6 relative'>
			<PolicyCard className='min-w-full md:min-w-60 lg:min-w-80 self-start h-auto md:sticky md:top-[100px]' />
			<aside className='col-span-5'>{children}</aside>
		</main>
	);
}
